CM-342: filter only not assigned bills
openimis/openimis-be-payroll_py pull request #15
Opened 2023-10-04 15:18 UTC by jdolkowski

https://openimis.atlassian.net/browse/CM-342

This PR filters only not assigned bills to payroll.

2023-10-04 15:53 UTC, dborowiecki reviewed
Not sure if that is a valid check. Can you confirm that it cover case when bill was detached from the payroll or when the bill is no longer valid?

2023-10-04 20:56 UTC, jdolkowski commented
I provided more strict filtering options.

2023-10-05 08:41 UTC, sniedzielski requested changes
@jdolkowski Please take a look into my comment

2023-10-05 08:41 UTC, sniedzielski commented on payroll/services.py
> +            Q(payrollbill__isnull=True) | Q(payrollbill__is_deleted=True)
Why payroll__is_deleted=True? 
I think that when we delete payroll, all bills are detached and moreover PayrollBill entity is completely removed. Can you confirm @jdolkowski

2023-10-05 08:56 UTC, jdolkowski commented on payroll/services.py
> +            Q(payrollbill__isnull=True) | Q(payrollbill__is_deleted=True)
PayrollBill.objects.filter(payroll=obj_).delete()  --> part from delete payroll

they are HistoryModel so they are set to is_deleted true

2023-10-05 09:13 UTC, sniedzielski commented on payroll/services.py
> +            Q(payrollbill__isnull=True) | Q(payrollbill__is_deleted=True)
ok, then it is ok

2023-10-05 09:13 UTC, sniedzielski approved these changes

2023-10-05 09:13 UTC, merged